// This file is generated by scripts/product-wiki.mjs. Do not edit by hand.
import spec_packages_plugins_expense_wiki_expense from '../../plugins/expense/wiki/expense/spec.json';
import spec_packages_plugins_growth_wiki_growth_goal from '../../plugins/growth/wiki/growth/goal/spec.json';
import spec_packages_plugins_growth_wiki_growth_habit from '../../plugins/growth/wiki/growth/habit/spec.json';
import spec_packages_plugins_growth_wiki_growth_repeat from '../../plugins/growth/wiki/growth/repeat/spec.json';
import spec_packages_plugins_growth_wiki_growth from '../../plugins/growth/wiki/growth/spec.json';
import spec_packages_plugins_growth_wiki_growth_task from '../../plugins/growth/wiki/growth/task/spec.json';
import spec_packages_plugins_growth_wiki_growth_todo from '../../plugins/growth/wiki/growth/todo/spec.json';
import spec_packages_plugins_growth_wiki_growth_track_time from '../../plugins/growth/wiki/growth/track-time/spec.json';
import spec_packages_plugins_library_wiki_library from '../../plugins/library/wiki/library/spec.json';
import spec_packages_plugins_purchase_wiki_purchase from '../../plugins/purchase/wiki/purchase/spec.json';
import spec_packages_product_wiki_wiki_activity from '../wiki/activity/spec.json';
import spec_packages_product_wiki_wiki_ai_session from '../wiki/ai/session/spec.json';
import spec_packages_product_wiki_wiki_ai from '../wiki/ai/spec.json';
import spec_packages_product_wiki_wiki_app_shell from '../wiki/app-shell/spec.json';
import spec_packages_product_wiki_wiki_global from '../wiki/global/spec.json';
import spec_packages_product_wiki_wiki_notification from '../wiki/notification/spec.json';
import spec_packages_product_wiki_wiki_plugins from '../wiki/plugins/spec.json';
import spec_packages_product_wiki_wiki_setting from '../wiki/setting/spec.json';
import spec_packages_product_wiki_wiki_user from '../wiki/user/spec.json';
import spec_packages_product_wiki_wiki_workbench from '../wiki/workbench/spec.json';
import productHistory from '../wiki/changelog.json';

export const productWikis = [
  spec_packages_plugins_expense_wiki_expense,
  spec_packages_plugins_growth_wiki_growth_goal,
  spec_packages_plugins_growth_wiki_growth_habit,
  spec_packages_plugins_growth_wiki_growth_repeat,
  spec_packages_plugins_growth_wiki_growth,
  spec_packages_plugins_growth_wiki_growth_task,
  spec_packages_plugins_growth_wiki_growth_todo,
  spec_packages_plugins_growth_wiki_growth_track_time,
  spec_packages_plugins_library_wiki_library,
  spec_packages_plugins_purchase_wiki_purchase,
  spec_packages_product_wiki_wiki_activity,
  spec_packages_product_wiki_wiki_ai_session,
  spec_packages_product_wiki_wiki_ai,
  spec_packages_product_wiki_wiki_app_shell,
  spec_packages_product_wiki_wiki_global,
  spec_packages_product_wiki_wiki_notification,
  spec_packages_product_wiki_wiki_plugins,
  spec_packages_product_wiki_wiki_setting,
  spec_packages_product_wiki_wiki_user,
  spec_packages_product_wiki_wiki_workbench,
];

export { productHistory };
