// This file is generated by scripts/product-wiki.mjs. Do not edit by hand.
import spec_ai_session from '../wiki/ai/session/spec.json';
import spec_ai from '../wiki/ai/spec.json';
import spec_global from '../wiki/global/spec.json';
import spec_growth_goal from '../wiki/growth/goal/spec.json';
import spec_growth_habit from '../wiki/growth/habit/spec.json';
import spec_growth_repeat from '../wiki/growth/repeat/spec.json';
import spec_growth from '../wiki/growth/spec.json';
import spec_growth_task from '../wiki/growth/task/spec.json';
import spec_growth_todo from '../wiki/growth/todo/spec.json';
import spec_growth_track_time from '../wiki/growth/track-time/spec.json';
import productHistory from '../wiki/changelog.json';

export const productWikis = [
  spec_ai_session,
  spec_ai,
  spec_global,
  spec_growth_goal,
  spec_growth_habit,
  spec_growth_repeat,
  spec_growth,
  spec_growth_task,
  spec_growth_todo,
  spec_growth_track_time,
];

export { productHistory };
