module.exports = {
  displayName: 'life-toolkit-server',
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/**/*.spec.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.entity.ts',
    '!src/**/*.module.ts',
    '!src/main.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@life-toolkit/vo$': '<rootDir>/../../packages/vo/src/index.ts',
    '^@life-toolkit/components-repeat$': '<rootDir>/../../packages/components-repeat/src/index.ts',
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  testTimeout: 30000,
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
  globalSetup: '<rootDir>/test/global-setup.ts',
  globalTeardown: '<rootDir>/test/global-teardown.ts',
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/coverage/'],
  verbose: true,
  detectOpenHandles: true,
  forceExit: true,
  maxWorkers: 1,
};
