import { useMemo, useState } from 'react';
import { Alert, Button, Card, Checkbox, Drawer, Flex, Modal, Space, Tag, message } from '@sue/design-web-react';
import { createDefaultRepeatSetting } from '@true-north/components-repeat';
import type { AiSuggestion, DrawerKind, DrawerState, Goal, Habit, SaveEntity, Task, Todo } from '../../shared/types';
import { productRef } from '../../product-wiki';
import { addDays } from '../../shared/utils';
import { TODAY } from '../../shared/mock-data';
import { drawerPaddedBodyStyles } from '../../shared/drawerStyles';
import styles from './index.module.css';

type Props = { open: boolean; goalId: string; goals: Goal[]; tasks: Task[]; todos: Todo[]; habits: Habit[]; setDrawer: (drawer: DrawerState) => void; saveEntity: SaveEntity; onClose: () => void };
export function AiDecompositionDrawer({ open, goalId, goals, tasks, todos, habits, setDrawer, saveEntity, onClose }: Props) {
  const [selected, setSelected] = useState<string[]>([]); const [accepted, setAccepted] = useState<string[]>([]); const [batchOpen, setBatchOpen] = useState(false);
  const target = goals.find((goal) => goal.id === goalId) || goals[0];
  const suggestions = useMemo<AiSuggestion[]>(() => { const start = addDays(TODAY, 1); const hasResearch = tasks.some((task) => task.goalId === target.id && task.title.includes('访谈')); return [
    { id: `${target.id}-subgoal`, kind: 'goal', title: `${target.title} · 用户验证`, goalId: target.id, parentId: target.id, planned: start, importance: Math.min(5, target.importance), difficulty: Math.min(5, target.difficulty), impact: '形成可度量的阶段性交付，降低目标过于抽象的风险。', reason: '当前目标缺少可验证的阶段性拆分。', conflict: goals.some((goal) => goal.parentId === target.id && goal.title.includes('用户验证')) ? '已存在相近子目标' : undefined },
    { id: `${target.id}-task`, kind: 'task', title: `为“${target.title}”安排关键行动`, goalId: target.id, planned: start, importance: target.importance, difficulty: Math.min(5, target.difficulty), impact: '明确本周责任事项，预计提升目标推进节奏。', reason: hasResearch ? '已有访谈任务，建议补充下一关键行动。' : '尚未发现直接关联的验证任务。' },
    { id: `${target.id}-todo`, kind: 'todo', title: `确认“${target.title}”的下一步`, goalId: target.id, planned: start, importance: target.importance, difficulty: 2, impact: '将高优先级行动落实为明日可执行待办。', reason: '目标存在进行中工作，适合设定一个最小下一步。' },
    { id: `${target.id}-habit`, kind: 'habit', title: `每日复盘“${target.title}”进展`, goalId: target.id, planned: start, importance: target.importance, difficulty: 2, impact: '建立稳定反馈回路，减少目标与日常行动脱节。', reason: habits.some((habit) => habit.goalIds.includes(target.id)) ? '已有习惯关联，可补充复盘维度。' : '当前没有关联习惯。' },
  ]; }, [goals, habits, target, tasks]);
  const adopt = (suggestion: AiSuggestion) => { if (suggestion.conflict) return message.warning('该建议存在重复冲突，请先跳过或调整'); const id = `${suggestion.kind[0]}${Date.now()}${Math.random().toString(16).slice(2, 5)}`; if (suggestion.kind === 'goal') saveEntity('goal', { id, title: suggestion.title, description: '由 AI 分层拆解建议创建。', parentId: suggestion.parentId, type: 'result', status: 'todo', importance: suggestion.importance, difficulty: suggestion.difficulty, start: target.start, end: target.end, history: ['AI 建议采纳'] }); if (suggestion.kind === 'task') saveEntity('task', { id, title: suggestion.title, description: '由 AI 拆解当前目标生成。', goalId: target.id, status: 'todo', importance: suggestion.importance, difficulty: suggestion.difficulty, plannedStart: suggestion.planned, plannedEnd: suggestion.planned, start: target.start, end: target.end, estimated: 2, actual: 0 }); if (suggestion.kind === 'todo') saveEntity('todo', { id, title: suggestion.title, description: '由 AI 拆解当前目标生成。', goalId: target.id, status: 'todo', importance: suggestion.importance, urgency: 3, planned: suggestion.planned, plannedStartTime: '09:00', plannedEndTime: '09:00', history: ['AI 建议采纳'] }); if (suggestion.kind === 'habit') saveEntity('habit', { id, title: suggestion.title, goalIds: [target.id], status: 'active', importance: suggestion.importance, difficulty: suggestion.difficulty, repeat: createDefaultRepeatSetting(suggestion.planned), streak: 0, longest: 0, logs: [] }); setAccepted((items) => [...items, suggestion.id]); };
  return <Drawer open={open} title="AI拆解" onClose={onClose} size="large" destroyOnHidden styles={drawerPaddedBodyStyles}><div data-product-ref={productRef('growth.goal.interaction')}><Flex vertical gap={16}><Flex className={styles.aiControls} justify="space-between" align="center" wrap="wrap" gap={12}><Tag color="blue">当前目标：{target.title}</Tag><Button disabled={!selected.length} onClick={() => setBatchOpen(true)}>采纳已选 {selected.length}</Button></Flex><Alert className={styles.aiAlert} type="info" showIcon title={`正在分析“${target.title}”的目标层级、${tasks.filter((task) => task.goalId === target.id).length} 项任务、${todos.filter((todo) => todo.goalId === target.id).length} 项待办与习惯反馈。`} />
    <Flex vertical className={styles.aiSuggestions} gap={12}>{suggestions.map((suggestion) => <Card size="small" key={suggestion.id} className={accepted.includes(suggestion.id) ? styles.accepted : undefined}><Flex justify="space-between" align="start" gap={12}><Space align="start"><Checkbox checked={selected.includes(suggestion.id)} disabled={Boolean(suggestion.conflict) || accepted.includes(suggestion.id)} onChange={(event) => setSelected((items) => event.target.checked ? [...items, suggestion.id] : items.filter((id) => id !== suggestion.id))} /><div><Tag color={suggestion.kind === 'goal' ? 'purple' : suggestion.kind === 'task' ? 'blue' : suggestion.kind === 'todo' ? 'gold' : 'green'}>{({ goal: '子目标', task: '任务', todo: '待办', habit: '习惯' } as Record<DrawerKind, string>)[suggestion.kind]}</Tag><h3>{suggestion.title}</h3><p>{suggestion.reason}</p><small>{suggestion.impact} · 计划 {suggestion.planned} · 重要 {suggestion.importance}</small>{suggestion.conflict && <Alert type="warning" showIcon title={suggestion.conflict} />}</div></Space><Space vertical><Button size="small" onClick={() => setDrawer({ kind: suggestion.kind })} disabled={accepted.includes(suggestion.id)}>编辑后采纳</Button><Button type="primary" size="small" disabled={Boolean(suggestion.conflict) || accepted.includes(suggestion.id)} onClick={() => adopt(suggestion)}>{accepted.includes(suggestion.id) ? '已采纳' : '采纳'}</Button></Space></Flex></Card>)}</Flex>
    <Modal title="批量采纳 AI 建议" open={batchOpen} onCancel={() => setBatchOpen(false)} onOk={() => { suggestions.filter((suggestion) => selected.includes(suggestion.id)).forEach(adopt); setSelected([]); setBatchOpen(false); }} okText="确认创建" cancelText="取消"><p>将逐条校验并创建所选建议。存在冲突的建议无法被勾选。</p></Modal>
  </Flex></div></Drawer>;
}
