export {
  PLUGIN_API_VERSION,
  PLUGIN_HUB_PATH,
  namespacedId,
  pluginPath,
  SHELL_SLOT_IDS,
  pluginManifestSchema,
  definePluginManifest,
  parsePluginManifest,
  contributionKey,
  hostStorageCapabilitySchema,
  captureSuggestionSchema,
  capturePayloadSchema,
  adoptCaptureRequestSchema,
  normalizeCaptureSuggestion,
  activityEntityRefSchema,
  ACTIVITY_RECORD_EVENT,
  ACTIVITY_UNLINK_EVENT,
  todaySectionKindSchema,
  todaySectionDescriptorSchema,
  todaySectionSnapshotSchema,
  mergeTodaySections,
  validateManifests,
  activationOrder,
  disposeOrder,
} from '@true-north/plugin-contract';
export type {
  PluginApiVersion,
  HostCapabilityId,
  ShellSlotId,
  PluginManifest,
  HostStorageCapability,
  PluginSpace,
  PluginRecord,
  PluginQueryPort,
  CaptureSuggestion,
  CapturePayload,
  AdoptCaptureRequest,
  CaptureAdopter,
  CaptureAdoptedLink,
  CaptureSuggestionStatus,
  ActivityEntityRef,
  ActivityLinkRef,
  CreateActivityInput,
  ActivityPort,
  TodaySectionKind,
  TodaySectionDescriptor,
  TodaySectionSnapshot,
  TodayListItem,
  TodayListItemAction,
  TodayCommand,
  CatalogIssue,
} from '@true-north/plugin-contract';

export { assemblePluginCatalog, reconcileMain, reconcileRenderer } from './catalog.ts';
export type { PluginCatalog, AssembledPlugin, AssembleCatalogOptions } from './catalog.ts';

export { defineMainImplementation, defineRendererImplementation } from './define.ts';
export type { TypedMainHandles } from './define.ts';

export { HostActionRegistry, WORKBENCH_EXTRACT_ACTION } from './runtime.ts';
export { HOST_WORKBENCH_OPEN, HOST_BROWSER_OPEN } from './host-commands.ts';
export type {
  AiCapability,
  AiCachePort,
  AgentTool,
  EntityResolver,
  AiContribution,
  WorkbenchHostActions,
  WorkbenchToolProps,
  WorkbenchToolDefinition,
  WorkbenchActionContribution,
  WorkbenchExtractHandler,
  WorkbenchWorkspaceHost,
  AiEntityRecord,
  AiEntitySource,
  PluginIcon,
  LocaleContribution,
  EntityPresenter,
  TodaySectionContribution,
  PluginIpcPort,
  HostActionPort,
  PluginMainContext,
  PluginMainHandles,
  PluginMainModule,
  PluginRendererContext,
  ShellSlotContribution,
  PluginRuntimeEntry,
  PluginRendererHandles,
  PluginRendererModule,
  PluginDescriptor,
} from './runtime.ts';

export { AiPlatformError, parseAiError, toIpcError } from './ai-error.ts';
