#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

turbo run pre-commit --filter=life-toolkit-webturbo run pre-commit --filter=life-toolkit-web
turbo run pre-commit --filter=life-toolkit-web
turbo run pre-commit --filter=life-toolkit-web
turbo run pre-commit --filter=life-toolkit-web
turbo run pre-commit --filter=life-toolkit-web
turbo run pre-commit --filter=life-toolkit-web
turbo run pre-commit --filter=life-toolkit-web
turbo run pre-commit --filter=life-toolkit-web
turbo run pre-commit --filter=life-toolkit-web
