version: '3.8'

services:
  life-toolkit-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: life-toolkit-server
    ports:
      - "3000:3000"
    env_file:
      - .env.development.local
    environment:
      # 默认环境变量（如果 .env 文件中没有定义）
      - NODE_ENV=production
      - PORT=3000
      # Docker 容器中需要使用 host.docker.internal 连接宿主机数据库
      - DB_HOST=host.docker.internal
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" 